-- Create initial products in database
-- Insert sample products for Si-Chic boutique
INSERT INTO products (
  id,
  name,
  description,
  price,
  category_id,
  image_url,
  images,
  material,
  colors,
  sizes,
  stock_quantity,
  is_available,
  is_featured,
  rating,
  review_count,
  created_at,
  updated_at
) VALUES
  (
    gen_random_uuid(),
    'Hijab Soie Premium Bordeaux',
    'Hijab en soie naturelle de qualité premium, doux et élégant',
    25000,
    NULL,
    '/elegant-bordeaux-silk-hijab.jpg',
    ARRAY['/elegant-bordeaux-silk-hijab.jpg'],
    'Soie naturelle',
    ARRAY['Bordeaux', 'Rose poudré', 'Champagne'],
    ARRAY['Unique'],
    50,
    true,
    true,
    4.8,
    124,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Abaya Moderne Noire Brodée',
    'Abaya moderne avec broderies délicates, parfaite pour toutes occasions',
    85000,
    NULL,
    '/modern-black-embroidered-abaya.jpg',
    ARRAY['/modern-black-embroidered-abaya.jpg'],
    'Crêpe de luxe',
    ARRAY['Noir', 'Bleu marine', 'Bordeaux'],
    ARRAY['S', 'M', 'L', 'XL'],
    30,
    true,
    true,
    4.9,
    89,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Ensemble Professionnel Beige',
    'Ensemble élégant pour le bureau, confortable et chic',
    65000,
    NULL,
    '/professional-beige-hijab-outfit.jpg',
    ARRAY['/professional-beige-hijab-outfit.jpg'],
    'Polyester premium',
    ARRAY['Beige', 'Gris', 'Rose'],
    ARRAY['S', 'M', 'L', 'XL'],
    25,
    true,
    false,
    4.7,
    156,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Hijab Sport Respirant Rose',
    'Hijab technique pour le sport, respirant et confortable',
    18000,
    NULL,
    '/breathable-pink-sports-hijab.jpg',
    ARRAY['/breathable-pink-sports-hijab.jpg'],
    'Polyester recyclé',
    ARRAY['Rose', 'Gris', 'Noir'],
    ARRAY['Unique'],
    60,
    true,
    false,
    4.6,
    78,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Abaya Cérémonie Dorée',
    'Abaya de cérémonie avec broderies dorées, luxueuse et raffinée',
    120000,
    NULL,
    '/golden-ceremony-abaya-elegant.jpg',
    ARRAY['/golden-ceremony-abaya-elegant.jpg'],
    'Satin brodé or',
    ARRAY['Doré', 'Champagne', 'Ivoire'],
    ARRAY['S', 'M', 'L', 'XL'],
    15,
    true,
    true,
    5.0,
    45,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Hijab Mousseline Bleu Ciel',
    'Hijab léger en mousseline, parfait pour l''été',
    22000,
    NULL,
    '/sky-blue-chiffon-hijab-flowing.jpg',
    ARRAY['/sky-blue-chiffon-hijab-flowing.jpg'],
    'Mousseline de soie',
    ARRAY['Bleu ciel', 'Blanc', 'Rose poudré'],
    ARRAY['Unique'],
    45,
    true,
    false,
    4.5,
    92,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Abaya Quotidienne Grise',
    'Abaya confortable pour tous les jours, coupe moderne',
    55000,
    NULL,
    '/elegant-grey-daily-abaya-modest-fashion.jpg',
    ARRAY['/elegant-grey-daily-abaya-modest-fashion.jpg'],
    'Jersey premium',
    ARRAY['Gris', 'Noir', 'Taupe'],
    ARRAY['S', 'M', 'L', 'XL'],
    35,
    true,
    false,
    4.7,
    134,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Ensemble Sport Complet Noir',
    'Ensemble complet pour le sport, technique et élégant',
    45000,
    NULL,
    '/black-sports-hijab-outfit-athletic-wear.jpg',
    ARRAY['/black-sports-hijab-outfit-athletic-wear.jpg'],
    'Tissu technique',
    ARRAY['Noir', 'Gris', 'Marine'],
    ARRAY['S', 'M', 'L', 'XL'],
    40,
    true,
    false,
    4.8,
    67,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Hijab Satin Champagne',
    'Hijab en satin luxueux, brillance subtile et élégante',
    28000,
    NULL,
    '/champagne-satin-hijab-luxury-fabric.jpg',
    ARRAY['/champagne-satin-hijab-luxury-fabric.jpg'],
    'Satin de soie',
    ARRAY['Champagne', 'Or rose', 'Beige'],
    ARRAY['Unique'],
    55,
    true,
    true,
    4.9,
    112,
    NOW(),
    NOW()
  )
ON CONFLICT (id) DO NOTHING;
